### ISSUE TITLE
reporte diagramas de componentes

### ISSUE THREAD

**Issue by Luisangelriverosbautista** [SistemasTecTlaxiaco/actividad-10-practica-de-arquitectura-equpio-lor-xd#1]
[DIAGRAMAS DE COMPONENTES REPORTE.pdf](https://github.com/user-attachments/files/17985467/DIAGRAMAS.DE.COMPONENTES.REPORTE.pdf)

**Comment by Reyesjessica** [comment]
28 cumple con casi todo lo requerido

**Comment by josealfredo79** [comment]
falta mas texto en la conclusion...
